
# Site settings
title: Rigs of Rods documentation
name: Local Rigs of Rods Documentation

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-redirect-from
  