site_name: Rigs of Rods documentation
site_description: Rigs of Rods project documentation
site_author: Rigs of Rods Community
site_url: https://docs.rigsofrods.org/

docs_dir: source

repo_name: RigsOfRods/docs.rigsofrods.org
repo_url: https://github.com/RigsOfRods/docs.rigsofrods.org
edit_uri: blob/master/source/

copyright: "Copyright &copy; 2020 Rigs of Rods Community"

theme:
  name: "material"
  favicon: ror-favicon.png
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - instant
    - tabs

plugins:
  - search # necessary for search to work
  - git-revision-date-localized
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
