site_name: Rigs of Rods Documentation
site_description: Rigs of Rods project documentation
site_author: Rigs of Rods contributors
site_url: https://rigsofrods.org/
copyright: <a href="https://docs.rigsofrods.org/" target="_blank">End-user documentation for the Rigs of Rods project. &copy; 2013-2024 Rigs of Rods documentation contributors.</a>

docs_dir: source

repo_name: RigsOfRods/docs.rigsofrods.org
repo_url: https://github.com/RigsOfRods/docs.rigsofrods.org
edit_uri: blob/master/source/

theme:
  name: "material"
  favicon: ror-favicon.png
  logo: images/branding/RoR_Logo_TT.png
  font:
    text: Maven Pro
  features:
    - content.action.edit
    - content.action.view
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Light

  features:
    - navigation.instant
    - navigation.footer
    #- toc.integrate
    - content.code.annotate
    - navigation.top

extra_css:
  - stylesheets/ror.css

plugins:
  - search # necessary for search to work
  - git-committers:
      repository: RigsOfRods/docs.rigsofrods.org
  - git-revision-date-localized
  - minify:
      minify_html: true
  - redirects:
      redirect_maps:
        'rules/rules-stolen-content.md': 'rules/community-guidelines.md#dont-steal-content-or-violate-intellectual-property'

nav:
  - Overview: README.md
  - Gameplay:
      - Installing the game: gameplay/installing-the-game.md
      - General FAQ: gameplay/general-faq.md
      - Common issues: gameplay/common-issues.md
      - Beginner's Guide: gameplay/beginners-guide.md
      - Installing content (mods): gameplay/installing-content.md
      - Controls and configuration: gameplay/controls-config.md
      - Vehicle AI: gameplay/vehicle-ai.md
      - Tuning menu: gameplay/tuning.md
      - Aircraft handling: gameplay/aircraft-handling.md
      - Multiplayer server setup: gameplay/multiplayer-server-setup.md
      - Version 2020.01 FAQ: gameplay/version-2020-01-faq.md
      - Jargon: gameplay/jargon.md
  - Tools and tutorials:
      - Installing addons (Manual): tools-tutorials/addons.md
      - Modifying suspension (lifting, lowering, width, camber): tools-tutorials/modding-suspension.md
      - Blender (2.7) mesh editing: tools-tutorials/blender-mesh-editing.md
      - Editor nodeSnap: tools-tutorials/editor-nodeSnap.md
      - Visual editors: tools-tutorials/visual-editors.md
      - How to contribute to community projects using GitHub: tools-tutorials/contributing-github.md
      - Documentation contributing guide {How to edit the docs): tools-tutorials/docs-contributing-guide.md
      - Branding: tools-tutorials/branding.md
  - Vehicle creation:
      - Truck file format: vehicle-creation/fileformat-truck.md
      - Soundscript file format: vehicle-creation/fileformat-soundscript.md
      - Addonpart file format: vehicle-creation/fileformat-addonpart.md
      - Alternate skins (skinzips): vehicle-creation/alternate-skins.md
      - Engine: vehicle-creation/engine.md
      - Flares: vehicle-creation/flares.md
      - Flexbody wheels: vehicle-creation/flexbody-wheels.md
      - Flexbody deforming/detaching parts: vehicle-creation/flexbody-deforming-detaching-parts.md
      - Aircraft and aerodynamics: vehicle-creation/aircraft-and-aerodynamics.md
      - Rail vehicles: vehicle-creation/rail-vehicles.md
      - Boats: vehicle-creation/boats.md
      - Motorbikes: vehicle-creation/motorbikes.md
      - Tracked vehicles: vehicle-creation/tracked-vehicles.md
      - Vehicle (Node/Beam) concepts: vehicle-creation/vehicle-concepts.md
      - Suspension: vehicle-creation/suspension.md
      - Wheels, axles, steering: vehicle-creation/wheels-axles-steering.md
      - Special components: vehicle-creation/special-components.md
      - Weight tuning: vehicle-creation/weight-tuning.md
      - Making custom dashboard HUD: vehicle-creation/making-custom-hud.md
  - Terrain creation:
      - Terrn2 file format: terrain-creation/terrn2-subsystem.md
      - Converting old terrain to terrn2 format: terrain-creation/terrain-conversion-terrn2.md
      - Editing terrain objects: terrain-creation/editing-terrain-objects.md
      - Object (odef) file format: terrain-creation/object-format.md
      - Collision meshes: terrain-creation/collision-meshes.md
      - L3DT Map Making: terrain-creation/l3dt-map-making.md
      - Shadows: terrain-creation/shadows.md
      - Building rail tracks: terrain-creation/building-rail-tracks.md
      - Race script generator: terrain-creation/race-generator.md
      - Scripting: terrain-creation/scripting.md
      - RAW Heightmaps: terrain-creation/raw-heightmaps.md
      - Alpha splatting: terrain-creation/custom-texture-splatting.md
      - Old (0.3x) terrain file format: terrain-creation/old-terrn-subsystem.md
  - Rules:
      - Community Guidelines: rules/community-guidelines.md
      - Forum Rules: rules/forum-rules.md
      - Repository Submission Guidelines: rules/repository-submission-guidelines.md
      - Contributor Code of Conduct: rules/contributor-code-of-conduct.md
      - Multiplayer Rules to Play By: rules/multiplayer-rules-to-play-by.md
      - Privacy Policy: rules/privacy-policy.md
      - Terms of Service: rules/terms-of-service.md
      - Project Governance: rules/project-governance.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/x-twitter
      name: Rigs of Rods on X
      link: https://x.com/rigsofrods
    - icon: fontawesome/brands/discord
      name: Rigs of Rods on Discord
      link: https://discord.gg/rigsofrods
    - icon: fontawesome/brands/youtube
      name: Rigs of Rods on YouTube
      link: https://youtube.com/@rigsofrods_official
    - icon: fontawesome/brands/mastodon
      name: Rigs of Rods on Mastodon
      link: https://fosstodon.org/@rigsofrods
    - icon: fontawesome/brands/facebook
      name: Rigs of Rods on Facebook
      link: https://facebook.com/RigsOfRods

  generator: false
