name: Check spelling

on: [push, pull_request]

jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install --upgrade pip setuptools
        pip install pyspelling

    - name: Install Aspell
      run: |
        sudo apt-get install aspell aspell-en

    - name: Spell check
      run: |
        python -m pyspelling